# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

# We exclude src/ssdeep-lib/ from some check because we don't
# want to fix external code in this repository

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # Require literal syntax when initializing empty or zero Python builtin types
      - id: check-builtin-literals
      # Check for files that would conflict in case-insensitive filesystems
      - id: check-case-conflict
      # Ensures that (non-binary) executables have a shebang
      - id: check-executables-have-shebangs
      # Check for files that contain merge conflict strings
      - id: check-merge-conflict
      # Checks for symlinks which do not point to anything
      - id: check-symlinks
      # This hook checks yaml files for parseable syntax
      - id: check-yaml
        files: .drone.yml
        # Drone CI config allows and requires multiple documents
        args: [--allow-multiple-documents]
      - id: check-yaml
        exclude: .drone.yml
      # Detects the presence of private keys
      - id: detect-private-key
      # Ensures that a file is either empty, or ends with one newline
      - id: end-of-file-fixer
      # Replaces or checks mixed line ending
      - id: mixed-line-ending
      # This hook trims trailing whitespace
      - id: trailing-whitespace

# TODO: Make this functional!
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.100.0
    hooks:
      - id: terraform_fmt
      #- id: terraform_docs
      - id: terraform_validate
        args:
          - --tf-init-args=-upgrade
          - --tf-init-args=-lockfile=readonly

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      # Detect common mistake of using single backticks when writing rst
      - id: rst-backticks
      # Detect mistake of inline code touching normal text in rst
      - id: rst-inline-touching-normal
      # Forbid files which have a UTF-8 Unicode replacement character
      - id: text-unicode-replacement-char
