name: opentofu-plan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  opentofu-plan:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y --no-install-recommends \
          libvirt-daemon \
          libvirt-daemon-driver-qemu \
          libvirt-daemon-system \
          libvirt-daemon-system-systemd \
          qemu-system-x86 \
          qemu-utils
        sudo setfacl --modify user:${USER}:rw /var/run/libvirt/libvirt-sock
        sudo usermod -aG libvirt ${USER}
        sudo usermod -aG kvm ${USER}
        sudo newgrp libvirt
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Setup OpenTofu
      uses: opentofu/setup-opentofu@v1
    - name: tofu Fmt
      run: tofu fmt -check
    - name: tofu init
      run: tofu init
    - name: tofu validate
      run: tofu validate -no-color
    - name: tofu plan
      run: tofu plan -no-color
